"""Add event feedback

Revision ID: 010e86a9aca8
Revises: 08cc05eb333d
Create Date: 2016-07-31 11:12:54.524365

"""

# revision identifiers, used by Alembic.
revision = '010e86a9aca8'
down_revision = '08cc05eb333d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text(u"(now() at time zone 'utc')"), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text(u"(now() at time zone 'utc')"), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('attributes', postgresql.JSON(), server_default='{}', nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text(u'false'), nullable=False),
    sa.Column('comment', sa.Text(), server_default='', nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], [u'account.id'], name='feedback_account_id', ondelete='CASCADE', use_alter=True),
    sa.ForeignKeyConstraint(['event_id'], [u'event.id'], name='feedback_event_id', ondelete='CASCADE', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    ### end Alembic commands ###
