"""Add step order

Revision ID: 08cc05eb333d
Revises: c0f5bc243853
Create Date: 2016-07-22 20:50:11.639819

"""

# revision identifiers, used by Alembic.
revision = '08cc05eb333d'
down_revision = 'c0f5bc243853'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('step', sa.Column('order', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('step', 'order')
    ### end Alembic commands ###
