"""add plan items

Revision ID: 1e37354131ad
Revises: e762a632ef65
Create Date: 2017-07-23 13:41:27.419277

"""

# revision identifiers, used by Alembic.
revision = '1e37354131ad'
down_revision = 'e762a632ef65'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from geoalchemy2.types import Geography

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_item',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text(u"(now() at time zone 'utc')"), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text(u"(now() at time zone 'utc')"), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('attributes', postgresql.JSON(), server_default='{}', nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text(u'false'), nullable=False),
    sa.Column('title', sa.String(length=255), server_default='', nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('point', Geography(geometry_type='POINT', srid=4326), nullable=True),
    sa.Column('start_at', sa.DateTime(), nullable=True),
    sa.Column('finish_at', sa.DateTime(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], [u'event.id'], name='plan_item_event_id', ondelete='CASCADE', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plan_item')
    ### end Alembic commands ###
