"""Remove event destination

Revision ID: 2c0315b04bc7
Revises: 6ec0bd4c423a
Create Date: 2016-07-17 21:47:58.465363

"""

# revision identifiers, used by Alembic.
revision = '2c0315b04bc7'
down_revision = '6ec0bd4c423a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'destination')
    op.create_foreign_key('place_event_id', 'place', 'event', ['event_id'], ['id'], ondelete='CASCADE', use_alter=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('place_event_id', 'place', type_='foreignkey')
    op.add_column('event', sa.Column('destination', sa.VARCHAR(length=255), server_default=sa.text(u"''::character varying"), autoincrement=False, nullable=False))
    ### end Alembic commands ###
