"""Event secret unique index

Revision ID: 404b3881dd40
Revises: 010e86a9aca8
Create Date: 2017-02-25 15:14:06.237745

"""

# revision identifiers, used by Alembic.
revision = '404b3881dd40'
down_revision = '010e86a9aca8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'event', ['secret'])
    op.create_foreign_key('feedback_account_id', 'feedback', 'account', ['account_id'], ['id'], ondelete='CASCADE', use_alter=True)
    op.create_foreign_key('feedback_event_id', 'feedback', 'event', ['event_id'], ['id'], ondelete='CASCADE', use_alter=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('feedback_event_id', 'feedback', type_='foreignkey')
    op.drop_constraint('feedback_account_id', 'feedback', type_='foreignkey')
    op.drop_constraint(None, 'event', type_='unique')
    ### end Alembic commands ###
