"""add assignee

Revision ID: 570e23cbd079
Revises: a70b0a83fbbc
Create Date: 2016-03-20 01:01:37.323501

"""

# revision identifiers, used by Alembic.
revision = '570e23cbd079'
down_revision = 'a70b0a83fbbc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignee',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text(u"(now() at time zone 'utc')"), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text(u"(now() at time zone 'utc')"), nullable=True),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('step_id', sa.BigInteger(), nullable=False),
    sa.Column('resolution', sa.String(length=255), server_default='OPEN', nullable=False),
    sa.ForeignKeyConstraint(['account_id'], [u'account.id'], name='assignee_account_id', ondelete='CASCADE', use_alter=True),
    sa.ForeignKeyConstraint(['step_id'], [u'step.id'], name='assignee_step_id', ondelete='CASCADE', use_alter=True),
    sa.PrimaryKeyConstraint('account_id', 'step_id')
    )
    op.create_foreign_key('assignee_step_id', 'assignee', 'step', ['step_id'], ['id'], ondelete='CASCADE', use_alter=True)
    op.create_foreign_key('assignee_account_id', 'assignee', 'account', ['account_id'], ['id'], ondelete='CASCADE', use_alter=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('assignee_account_id', 'assignee', type_='foreignkey')
    op.drop_constraint('assignee_step_id', 'assignee', type_='foreignkey')
    op.drop_table('assignee')
    ### end Alembic commands ###
