"""add event

Revision ID: 5ed1a6ff7e24
Revises: 2a000acaabcc
Create Date: 2016-03-20 00:49:58.346541

"""

# revision identifiers, used by Alembic.
revision = '5ed1a6ff7e24'
down_revision = '2a000acaabcc'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), server_default='', nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('destination', sa.String(length=255), server_default='', nullable=False),
    sa.Column('status', sa.String(length=32), server_default='PREPARATION', nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('finish_at', sa.DateTime(), nullable=False),
    sa.Column('attributes', postgresql.JSON(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text(u'false'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text(u"(now() at time zone 'utc')"), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text(u"(now() at time zone 'utc')"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event')
    ### end Alembic commands ###
