"""session

Revision ID: 8e3898afc0d8
Revises: b90671508d1b
Create Date: 2016-03-08 17:50:16.920376

"""

# revision identifiers, used by Alembic.
revision = '8e3898afc0d8'
down_revision = 'b90671508d1b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('data', sa.PickleType(), nullable=True),
    sa.Column('expire_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session')
    ### end Alembic commands ###
