"""add participant

Revision ID: a70b0a83fbbc
Revises: fc4299a5158e
Create Date: 2016-03-20 00:58:08.862403

"""

# revision identifiers, used by Alembic.
revision = 'a70b0a83fbbc'
down_revision = 'fc4299a5158e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participant',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text(u"(now() at time zone 'utc')"), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text(u"(now() at time zone 'utc')"), nullable=True),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=255), server_default='ACTIVE', nullable=False),
    sa.Column('permissions', postgresql.JSON(), nullable=True),
    sa.Column('is_owner', sa.Boolean(), server_default=sa.text(u'false'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], [u'account.id'], name='participant_account_id', ondelete='CASCADE', use_alter=True),
    sa.ForeignKeyConstraint(['event_id'], [u'event.id'], name='participant_event_id', ondelete='CASCADE', use_alter=True),
    sa.PrimaryKeyConstraint('account_id', 'event_id')
    )
    op.create_foreign_key('participant_account_id', 'participant', 'account', ['account_id'], ['id'], ondelete='CASCADE', use_alter=True)
    op.create_foreign_key('participant_event_id', 'participant', 'event', ['event_id'], ['id'], ondelete='CASCADE', use_alter=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('participant_event_id', 'participant', type_='foreignkey')
    op.drop_constraint('participant_account_id', 'participant', type_='foreignkey')
    op.drop_table('participant')
    ### end Alembic commands ###
