"""fix

Revision ID: c0f5bc243853
Revises: 2c0315b04bc7
Create Date: 2016-07-19 22:52:13.490838

"""

# revision identifiers, used by Alembic.
revision = 'c0f5bc243853'
down_revision = '2c0315b04bc7'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('place', 'finish_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('place', 'start_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index('idx_place_point', table_name='place')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_place_point', 'place', ['point'], unique=False)
    op.alter_column('place', 'start_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('place', 'finish_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    ### end Alembic commands ###
